name: New Release
on:
  push:
    branches:
      - master
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
      - name: Get workerd version
        id: get_version
        run: |
          VERSION="$(cat release | awk '{ print $2 }')"
          echo "workerd version: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION }}.el9.x86-64
          release_name: Release ${{ env.VERSION }}.el9.x86-64
          draft: false
          prerelease: false      
